[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  SECRETS_SCAN_OMIT_PATHS = "*.md,scripts/*,PRIVACY_POLICY.md,GOOGLE_MEET_SETUP.md,NETLIFY_ENVIRONMENT_SETUP.md"

[context.production]
  command = "npm run build"
  
[context.branch-deploy]  
  command = "npm run build"

# Redirects for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
