[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[context.production]
  command = "npm run build"
  
[context.branch-deploy]  
  command = "npm run build"

# Next.js redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
